<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sc</string>
	</array>
	<key>name</key>
	<string>SecreC</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>variable types.</string>
			<key>match</key>
			<string>\b(bool|uint|uint8|uint16|uint32|uint64|int|int8|int16|int32|int64|float32|float64|xor_uint8|xor_uint16|xor_uint32|xor_uint64|float|void|string)\b</string>
			<key>name</key>
			<string>storage.type.secrec</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Numeric constants</string>
			<key>match</key>
			<string>\b(break|continue|do|else|for|if|return|while)\b</string>
			<key>name</key>
			<string>keyword.control.secrec</string>
		</dict>
		<dict>		
			<key>match</key>
			<string>\b([A-Z]([0-9]{0,1}))\b</string>
			<key>name</key>
			<string>keyword.type.secrec</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(template|domain|kind|dim|type|module|import|public)\b</string>
			<key>name</key>
			<string>storage.modifier.secrec</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>constant.language.secrec</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([0-9]+\.?[0-9]*)\b</string>
			<key>name</key>
			<string>constant.numeric.secrec</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(cat|size|shape|reshape|tostring|assert|declassify|__[A-Za-z]*)\b</string>
			<key>name</key>
			<string>support.function.any-method.secrec</string>
		</dict>
						
		<dict>
			<key>match</key>
			<string>(==|!=|&lt;=|&gt;=|&lt;&gt;|&lt;|&gt;)</string>
			<key>name</key>
			<string>keyword.operator.comparison.secrec</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(=)</string>
			<key>name</key>
			<string>keyword.operator.assignment.secrec</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\-\-|\+\+)</string>
			<key>name</key>
			<string>keyword.operator.increment-decrement.secrec</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.double-slash.secrec</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.secrec</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s*((//).*$\n?)</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.secrec</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.secrec</string>
		</dict>
	
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.secrec</string>
				</dict>
			</dict>
			<key>match</key>
			<string>/\*\*/</string>
			<key>name</key>
			<string>comment.block.empty.secrec</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\-|\+|\*|\/|%)</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.secrec</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(!|&amp;&amp;|\|\|)</string>
			<key>name</key>
			<string>keyword.operator.logical.secrec</string>
		</dict>		
		<dict>
			<key>match</key>
			<string>;</string>
			<key>name</key>
			<string>punctuation.terminator.secrec</string>
		</dict>

				
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.secrec</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.secrec</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.secrec</string>			
		</dict>
		
	</array>
	<key>scopeName</key>
	<string>source.secrec</string>
	<key>uuid</key>
	<string>dec1bca9-bac8-493f-9ed8-ced97e6a0ed3</string>
</dict>
</plist>
